version: '3'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --disable-partition-engine-check
    restart: always
    ports:
      - 3306:3306
    volumes:
       - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - db
    environment:
      PMA_HOST: db
#      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
